services:
  app:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      CLIENT_TOKEN: ${CLIENT_TOKEN}
      GUILD_ID_FALLEN_BERSERKERS: ${GUILD_ID_FALLEN_BERSERKERS}
      USER_ID_RPGOMES: ${USER_ID_RPGOMES}
      USER_ID_JPEREIRA: ${USER_ID_JPEREIRA}
      USER_ID_RPEREIRA: ${USER_ID_RPEREIRA}