services:
  isomeg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isomeg-bot
    restart: unless-stopped

    # Environment variables - Coolify will inject these
    environment:
      - NODE_ENV=production
      - CLIENT_TOKEN=${CLIENT_TOKEN}
      - GUILD_ID_FALLEN_BERSERKERS=${GUILD_ID_FALLEN_BERSERKERS}
      - USER_ID_RPGOMES=${USER_ID_RPGOMES}
      - USER_ID_JPEREIRA=${USER_ID_JPEREIRA}
      - USER_ID_RPEREIRA=${USER_ID_RPEREIRA}
      # Add any other environment variables your bot needs

    # Resource limits (adjust based on your VPS specs)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: If you need persistent data storage
volumes:
  bot_data:
    driver: local

# Optional: Custom network
networks:
  isomeg_network:
    driver: bridge